version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ../nginx/conf.dev/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - api
    networks:
      - nginx_network