# Generated by Django 4.2.13 on 2024-09-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Жооб')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Тузулгон убактысы')),
            ],
            options={
                'verbose_name': 'Жооб',
                'verbose_name_plural': 'Жообтор',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Суроо')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Сурот')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Тузулгон убактысы')),
            ],
            options={
                'verbose_name': 'Суроо',
                'verbose_name_plural': 'Суроолор',
            },
        ),
    ]
