version: '3'
services:
  api:
    build: .
    command: >
      sh -c "chmod +x run.sh && sh run.sh"
    container_name: tilimpoz
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media

  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - api


networks:
  nginx_network:
    driver: bridge


volumes:
  static_volume:
  media_volume:
