# Generated by Django 4.2.13 on 2024-08-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Аты')),
                ('photo', models.ImageField(upload_to='news/', verbose_name='Сурот')),
                ('date', models.DateField(verbose_name='Тузулгон убактысы')),
                ('description', models.TextField(verbose_name='Баяндалышы')),
            ],
            options={
                'verbose_name': 'Жанылык',
                'verbose_name_plural': 'Жанылыктар',
            },
        ),
    ]
