# Generated by Django 4.2.13 on 2024-09-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон номери')),
                ('email', models.EmailField(max_length=254, verbose_name='Уюлдук почтасы')),
                ('address', models.TextField(verbose_name='Дарек')),
                ('insta_link', models.URLField(blank=True, null=True, verbose_name='Инстаграм баракчасы')),
                ('tg_link', models.URLField(blank=True, null=True, verbose_name='Телеграм')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='Whatsapp дареги')),
                ('threads_link', models.URLField(blank=True, null=True, verbose_name='Threads баракчасы')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='Twitter баракчасы')),
            ],
            options={
                'verbose_name': 'Байланыш',
                'verbose_name_plural': 'Байланыштар',
            },
        ),
    ]
