# Generated by Django 4.2.13 on 2024-08-29 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон номери')),
                ('email', models.EmailField(max_length=254, verbose_name='Уюлдук почтасы')),
                ('address', models.TextField(verbose_name='Дарек')),
            ],
            options={
                'verbose_name': 'Байланыш',
                'verbose_name_plural': 'Байланыштар',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=350, verbose_name='Шилтеме')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='contacts.contact', verbose_name='Байланыштары')),
            ],
            options={
                'verbose_name': 'Социалдык тармак',
                'verbose_name_plural': 'Социалдык тармактар',
            },
        ),
    ]
