# Generated by Django 4.2.13 on 2024-09-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Баяндалышы')),
                ('photo', models.ImageField(upload_to='about/', verbose_name='Сурот')),
            ],
            options={
                'verbose_name': 'Биз жонундо',
                'verbose_name_plural': 'Биз жонундо',
            },
        ),
    ]
