# Generated by Django 4.2.13 on 2024-09-06 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Категориянын аталышы')),
            ],
            options={
                'verbose_name': 'Тесттин категориясы',
                'verbose_name_plural': 'Тесттин категориялары',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Тесттин аталышы')),
                ('image', models.ImageField(upload_to='test/', verbose_name='Тесттин суроту')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Макаланын категориясы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.testcategory', verbose_name='Тесттин категориясы')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесттер',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Тесттин суроосу')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Суроо',
                'verbose_name_plural': 'Суроолор',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Жооп')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Туурабы?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='Жооптун суроосу')),
            ],
            options={
                'verbose_name': 'Жооп',
                'verbose_name_plural': 'Жооптор',
            },
        ),
    ]
