# Generated by Django 4.2.13 on 2024-09-06 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Документтин аты')),
                ('photo', models.ImageField(upload_to='documents/', verbose_name='Сурот')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='categories.category', verbose_name='Категориясы')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документтер',
            },
        ),
    ]
