# Generated by Django 4.2.13 on 2024-09-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Суроо')),
                ('answer', models.TextField(verbose_name='Жооп')),
            ],
            options={
                'verbose_name': 'Эн коп берилген суроо',
                'verbose_name_plural': 'Эн коп берилген суроолор',
            },
        ),
    ]
