# Generated by Django 4.2.13 on 2024-09-06 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SozdukCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Аты')),
                ('image', models.ImageField(upload_to='sozduk/category/', verbose_name='Сурот')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sozduk', to='categories.category', verbose_name='Макаланын аты')),
            ],
            options={
                'verbose_name': 'Создуктун категориясы',
                'verbose_name_plural': 'Создуктун категориялары',
            },
        ),
        migrations.CreateModel(
            name='Sozduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Соз')),
                ('translation', models.CharField(max_length=200, verbose_name='Котормосу')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sozduk/sozdor/', verbose_name='Сурот')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soz', to='sozduk.sozdukcategory', verbose_name='Категориясы')),
            ],
            options={
                'verbose_name': 'Соз',
                'verbose_name_plural': 'Создор',
            },
        ),
    ]
