# Generated by Django 4.2.13 on 2024-07-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozduk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozduk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sozduk_images/'),
        ),
    ]
