"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import dotenv
import os
from . import ckeditor_settings
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG').lower() == 'true'
if DEBUG:
    from .db_dev import *
else:
    from .db_prod import *

ALLOWED_HOSTS = ['*']

# Application definition

MY_APPS = [
    'apps.users',
    'apps.rules',
    'apps.etymology',
    'apps.tilibizde',
    'apps.documents',
    'apps.books',
    'apps.categories',
    'apps.sozduk',
    'apps.about',
    'apps.qa',
    'apps.faq',
    'apps.contacts',
    'apps.team',
    'apps.news',
    'apps.quiz',
    'apps.sj',
    'apps.tuurajaz',
    'apps.videos',
]

ADMIN_THEME = [
    'unfold',
    'unfold.contrib.forms',
]

INSTALLED_PACKAGES = [
    'rest_framework',
    'debug_toolbar',
    'rest_framework_simplejwt',
    'drf_yasg',
    'corsheaders',
    'django_ckeditor_5',
    'django_filters',
    'nested_admin',
]

DJANGO_MODULES = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INSTALLED_APPS = [
    *ADMIN_THEME,
    *DJANGO_MODULES,
    *INSTALLED_PACKAGES,
    *MY_APPS
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

AUTH_USER_MODEL = 'users.CustomUser'

LANGUAGE_CODE = 'ky'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = BASE_DIR / 'static'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

customColorPalette = ckeditor_settings.customColorPalette

# CKEDITOR_5_CUSTOM_CSS = 'path_to.css'  # optional
# CKEDITOR_5_FILE_STORAGE = "path_to_storage.CustomStorage"  # optional
CKEDITOR_5_CONFIGS = ckeditor_settings.CKEDITOR_5_CONFIGS

# CKEditor Settings
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'

#Unfold Settings
UNFOLD = {
    "SITE_TITLE": "",
    "SITE_HEADER": "Тилимпоз башкармасы",
    "SITE_SYMBOL": "speed",
    "SITE_LOGO": {
        "light": lambda request: static("tilimpoz.png"),  # light mode
        "dark": lambda request: static("tilimpoz.png"),  # dark mode
    },
    "COLORS": {
        "font": {
            "subtle-light": "77 90 110",
            "subtle-dark": "105 118 139",
            "default-light": "40 55 75",
            "default-dark": "204 210 220",
            "important-light": "12 19 35",
            "important-dark": "235 240 245"
        },
        "primary": {
            "50": "225 239 255",
            "100": "198 224 254",
            "200": "165 203 252",
            "300": "124 174 251",
            "400": "90 145 238",
            "500": "54 116 225",
            "600": "38 89 205",
            "700": "28 67 179",
            "800": "24 54 148",
            "900": "22 45 118",
            "950": "16 30 83"
        }
    },
    "SIDEBAR": {
        "show_all_applications": False,
    },
    
    "STYLES": [
        lambda request: static("css/style.css"),
    ],
    
    "SCRIPTS": [
        lambda request: static("js/script.js"),
    ],
    
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5173',
    'http://tilimpoz1.vercel.app',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5173',
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000/',
    'http://47.237.85.188:80/',
    'http://127.0.0.1:8000/',
]

SWAGGER_SETTINGS = {
   'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'В форму пишете сначала слово "Bearer", затем пробел и access token'
        }
    }
}

