# Generated by Django 4.2.13 on 2024-08-29 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Аты')),
                ('category', models.CharField(default='General', max_length=255, verbose_name='Категория')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Тузулгон датасы')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Сурот')),
                ('description', models.TextField(verbose_name='Баяндалышы')),
            ],
            options={
                'verbose_name': 'Макала',
                'verbose_name_plural': 'Макалалар',
            },
        ),
    ]
