# Generated by Django 4.2.13 on 2024-09-06 20:18

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Аты')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Тузулгон датасы')),
            ],
            options={
                'verbose_name': 'Эреже',
                'verbose_name_plural': 'Эрежелер',
            },
        ),
    ]
